spring:
  application:
    name: beacon-core

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        provider_disables_autocommit: true
        type:
          json_format_mapper: beacon.config.Jackson3JsonFormatMapper

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        spring.json.add.type.headers: false
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      isolation-level: read_committed
      max-poll-records: 50
      properties:
        spring.json.value.default.type: "tools.jackson.databind.JsonNode"
        spring.json.trusted.packages: "beacon.event,tools.jackson"
    listener:
      ack-mode: record
      concurrency: 3

logging:
  level:
    root: WARN
    beacon: DEBUG